import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerated on every build by the `prebuild` npm script, so the REST API
// Reference below is always the real, Spectral-validated spec — never a
// hand-transcribed copy of it.
import restApiSidebar from './docs/api/rest/sidebar';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/index'},
      items: [
        'overview/what-it-does',
        'overview/hexagonal-layering',
        'overview/running-locally',
      ],
    },
    {
      type: 'category',
      label: 'Business Context',
      link: {type: 'doc', id: 'business-context/index'},
      items: [
        'business-context/domain-vision',
        'business-context/ubiquitous-language',
        'business-context/why-waveless-release',
        'business-context/flow-balancing',
      ],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      link: {type: 'doc', id: 'ddd/index'},
      items: [
        'ddd/subdomain-classification',
        {
          type: 'category',
          label: 'DDD artifacts (ddd-crew)',
          link: {type: 'doc', id: 'ddd/ddd-artifacts'},
          items: [
            'ddd/core-domain-chart',
            'ddd/bounded-context-canvas',
            'ddd/aggregate-design-canvas',
            'ddd/domain-message-flow',
            'ddd/eventstorming',
            'ddd/class-diagram',
            'ddd/entity-relationship',
            'ddd/sequence-diagrams',
          ],
        },
        'ddd/domain-events',
        'ddd/read-models',
        'ddd/context-relationships',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api/index'},
      items: [
        {
          type: 'category',
          label: 'REST API',
          link: {type: 'doc', id: 'api/rest-overview'},
          items: restApiSidebar,
        },
        'api/events',
        'api/errors',
      ],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      link: {type: 'doc', id: 'ecosystem/index'},
      items: [
        'ecosystem/context-map',
        'ecosystem/integration-events',
        'ecosystem/sibling-services',
        'ecosystem/flowfed-observed-throughput',
      ],
    },
    {
      type: 'category',
      label: 'AI Ecosystem (MCP)',
      collapsed: false,
      items: ['mcp/governance-charter'],
    },
    {
      type: 'category',
      label: 'Analytics (Data Product)',
      collapsed: false,
      items: ['analytics/release-throughput-report'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/index'},
      items: [
        'adr/0001-hexagonal-ports-and-adapters',
        'adr/0002-waveless-continuous-release',
        'adr/0003-flow-balancing-as-domain-service',
        'adr/0004-kafka-integration-events',
        'adr/0005-rfc-7807-problem-details',
        'adr/0006-labor-plan-view-not-shift-plan',
        'adr/0007-arch-go-fitness-tests',
        'adr/0008-mcp-inbound-adapter',
        'adr/0009-product-classification-propagation-to-work-released',
        'adr/0010-gift-wrap-as-a-work-released-characteristic',
        'adr/0011-analytical-data-product',
        'adr/0012-process-path-catalogue-validation',
        'adr/0013-standard-metrics-convention',
        'adr/0014-transactional-outbox',
        'adr/0015-rest-identity-static-bearer-scopes',
        'adr/0016-remove-rest-mcp-static-bearer-auth',
        'adr/0017-travel-distance-lookup-on-commit-shift-plan',
        'adr/0018-path-capacity-changed',
        'adr/0019-labor-plan-committed-shift-plan-reconciliation',
        'adr/0020-flowfed-path-observed-throughput-signal',
        'adr/0021-cloudevents-envelope-migration',
        'adr/0022-idempotency-key-middleware',
        'adr/0023-resilience-circuit-breakers-retry-dlq-shutdown',
        'adr/0024-kafka-hash-balancer-partition-affinity',
        'adr/0025-horizontal-autoscaling-and-pgxpool-tuning',
        'adr/0026-migrations-direct-postgres-connection',
        'adr/0027-cloudevents-mandatory-event-envelope',
        'adr/0028-processed-event-mark-atomic-with-handling',
        'adr/0029-work-pool-optimistic-concurrency',
        'adr/0030-kafka-sourced-path-catalogue',
        'adr/0031-order-allocated-choreography',
        'adr/0032-housekeeping-retention-sweeper',
      ],
    },
  ],
};

export default sidebars;
